config/routes.rb
Rails.application.routes.draw do
  resources :escogidos
  resources :memos
  resources :alternativos
  resources :docderivaciones
  resources :derivaciones
  resources :items
  resources :ruta
  resources :documentos
  resources :compras
  resources :caminos
  resources :gestiones
  resources :unidades
  resources :cargos
  # devise_for :users
  get "reportes/tramites"
  get "reportes/fechas"

  # get '/users/sign_in', to: 'users/sessions#new', as: 'new_user_session'
  # post '/users/sign_in', to: 'users/sessions#create', as: 'user_session'
  devise_for :users, path: "usuarios", controllers: {sessions: "users/sessions"}
  # devise_for :users, path: 'usuarios', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :users
  # resources :cotizaciones
  get "welcome/index"

  root :to => "users#index"
  # root :to => 'panelcontrols#index'

  # devise_scope :user do
  #   get '/usuarios/sign_in', to: 'users/sessions#new', as: 'new_user_session'
  # end
  get "/compra/mis_compras/:usuario", to: "compras#mis_compras", as: "mis_compras"
  get "/cargo/excel", to: "cargos#excel", as: "cargos_excel"

  get "/rutas/ver_caminos/:id_ruta", to: "ruta#ver_caminos", as: "ruta_ver_caminos"
  get "/rutas/eliminar/:id_ruta", to: "ruta#eliminar", as: "ruta_eliminar"
  post "/rutas/guarda_camino", to: "ruta#guarda_camino", as: "ruta_guarda_camino"
  post "/rutas/crear", to: "ruta#crear", as: "ruta_crear"
  get "/rutas/muestra_funcionarios/:id_unidad", to: "ruta#muestra_funcionarios", as: "ruta_muestra_funcionario"
  get "/rutas/muestra_cargos/:id_unidad", to: "ruta#muestra_cargos", as: "ruta_muestra_cargos"
  get "/rutas/editar/:id_ruta", to: "ruta#editar", as: "ruta_editar"
  patch "/rutas/guarda_editado", to: "ruta#guarda_editado", as: "ruta_guarda_editado"

  get "/user/inicio", to: "users#inicio", as: "users_inicio"

  get "/compra/mis_tramites", to: "compras#mis_tramites", as: "compras_mis_tramites"
  get "/compra/imprime_solicitud/:id_compra", to: "compras#imprime_solicitud", as: "compras_imprime_solicitud"
  get "/compra/edita_compra/:id_compra", to: "compras#edita_compra", as: "compras_edita_compra"
  get "/compra/asignar/:id_compra", to: "compras#asignar", as: "compras_asignar"
  post "/compra/completa_solicitud", to: "compras#completa_solicitud", as: "compras_completa_solicitud"
  get "/compra/bandeja_entrada", to: "compras#bandeja_entrada", as: "compras_bandeja_entrada"
  get "/compra/carga_excepcion", to: "compras#carga_excepcion", as: "compras_carga_excepcion"
  get "/compra/ver_documento/:id_compra", to: "compras#ver_documento", as: "compras_ver_documento"
  get "/compra/ver_adjunto/:id_compra", to: "compras#ver_adjunto", as: "compras_ver_adjunto"

  get "/derivacione/ver_documento/:id_derivacion", to: "derivaciones#ver_documento", as: "derivaciones_ver_documento"
  get "/derivacione/ver_documento_rpa/:id_derivacion", to: "derivaciones#ver_documento_rpa", as: "derivaciones_ver_documento_rpa"
  post "/derivacione/guarda_derivacion", to: "derivaciones#guarda_derivacion", as: "derivaciones_guarda_derivacion"
  get "/derivacione/ver_derivaciones/:id_compra", to: "derivaciones#ver_derivaciones", as: "derivaciones_ver_derivaciones"
  get "/derivacione/ver_documento_jefe/:id_derivacion", to: "derivaciones#ver_documento_jefe", as: "derivaciones_ver_documento_jefe"
  get "/derivacione/ver_memo", to: "derivaciones#ver_memo", as: "derivaciones_ver_memo"
  post "/derivacione/genera_memo", to: "derivaciones#genera_memo", as: "derivaciones_genera_memo"
  get "/derivacione/ve_genera_memo/:id_memo", to: "derivaciones#ve_genera_memo", as: "derivaciones_ve_genera_memo"

  get "/camino/eliminar/:id_camino/:cod_ruta", to: "caminos#eliminar", as: "camino_eliminar"
  get "/camino/carga_funcionario/:proceso", to: "caminos#carga_funcionario", as: "camino_carga_funcionario"
  get "/camino/carga_funcionario_alternativo/:id_alternativo/:id_compra", to: "caminos#carga_funcionario_alternativo", as: "camino_carga_funcionario_alternativo"

  get "/documento/nuevo/:id_camino", to: "documentos#nuevo", as: "documento_nuevo"
  post "/documento/guarda_nuevo", to: "documentos#guarda_nuevo", as: "documento_guarda_nuevo"
  get "/documento/eliminar/:id_documento/:id_camino", to: "documentos#eliminar", as: "documento_eliminar"
  get "/documento/memos/:id_camino", to: "documentos#memos", as: "documento_memos"
  post "/documento/guarda_memo", to: "documentos#guarda_memo", as: "documento_gurada_memo"
  get "/documento/elimina_memo/:id_memo/:id_camino", to: "documentos#elimina_memo", as: "documento_elimina_memo"

  get "/alternativo/nuevo/:id_camino", to: "alternativos#nuevo", as: "alternativos_nuevo"
  post "/alternativo/guarda_nuevo", to: "alternativos#guarda_nuevo", as: "alternativos_guarda_nuevo"
  get "/alternativo/eliminar/:id_alternativo/:id_camino", to: "alternativos#eliminar", as: "alternativos_eliminar"
  # get "/alternativo/muestra_alternativos/:id_camino", to: "alternativos#nuevo", as: "alternativos_nuevo"

  get "/reportes/tramites", to: "reportes#tramites", as: "reporte_tramites"
  post "/reportes/por_numero", to: "reportes#por_numero", as: "reporte_por_numero"
  post "/reportes/por_usuario", to: "reportes#por_usuario", as: "reporte_por_usuario"
  post "/reportes/por_fecha", to: "reportes#por_fecha", as: "reporte_por_fecha"
  post "/reportes/por_unidad", to: "reportes#por_unidad", as: "reporte_por_unidad"

  get "/memo/imprime/:id_memo", to: "memos#imprime", as: "memo_imprime"
  # devise_for :users, path: 'auth', path_names: {  sign_out: 'logout', sign_up: 'cmon_let_me_in' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/unidade.rb
class Unidade < ApplicationRecord
end

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :set_unidade, only: [:show, :edit, :update, :destroy]
  layout "template"
  # GET /unidades
  # GET /unidades.json
  def index
    @unidades = Unidade.all
  end

  # GET /unidades/1
  # GET /unidades/1.json
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades
  # POST /unidades.json
  def create
    @unidade = Unidade.new(unidade_params)

    respond_to do |format|
      if @unidade.save
        format.html { redirect_to @unidade, notice: 'Unidade was successfully created.' }
        format.json { render :show, status: :created, location: @unidade }
      else
        format.html { render :new }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidades/1
  # PATCH/PUT /unidades/1.json
  def update
    respond_to do |format|
      if @unidade.update(unidade_params)
        format.html { redirect_to @unidade, notice: 'Unidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @unidade }
      else
        format.html { render :edit }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1
  # DELETE /unidades/1.json
  def destroy
    @unidade.destroy
    respond_to do |format|
      format.html { redirect_to unidades_url, notice: 'Unidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidade
      @unidade = Unidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unidade_params
      params.require(:unidade).permit(:descripcion, :estado)
    end
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/unidades/_form.html.erb
<%= form_with(model: unidade, local: true) do |form| %>
  <% if unidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unidade.errors.count, "error") %> prohibited this unidade from being saved:</h2>

      <ul>
      <% unidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :unidade_descripcion %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.number_field :estado, id: :unidade_estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unidades/edit.html.erb
<h1>Editing Unidade</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to 'Show', @unidade %> |
<%= link_to 'Back', unidades_path %>

app/views/unidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unidades</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unidades.each do |unidade| %>
      <tr>
        <td><%= unidade.descripcion %></td>
        <td><%= unidade.estado %></td>
        <td><%= link_to 'Mostrar', unidade %></td>
        <td><%= link_to 'Editar', edit_unidade_path(unidade) %></td>
        <td><%= link_to 'Eliminar', unidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Unidad', new_unidade_path %>

app/views/unidades/new.html.erb
<h1>Nueva Unidad</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to 'Atras', unidades_path %>

app/views/unidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @unidade.descripcion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @unidade.estado %>
</p>

<%= link_to 'Edit', edit_unidade_path(@unidade) %> |
<%= link_to 'Back', unidades_path %>