config/routes.rb
Rails.application.routes.draw do
  resources :escogidos
  resources :memos
  resources :alternativos
  resources :docderivaciones
  resources :derivaciones
  resources :items
  resources :ruta
  resources :documentos
  resources :compras
  resources :caminos
  resources :gestiones
  resources :unidades
  resources :cargos
  # devise_for :users
  get "reportes/tramites"
  get "reportes/fechas"

  # get '/users/sign_in', to: 'users/sessions#new', as: 'new_user_session'
  # post '/users/sign_in', to: 'users/sessions#create', as: 'user_session'
  devise_for :users, path: "usuarios", controllers: {sessions: "users/sessions"}
  # devise_for :users, path: 'usuarios', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :users
  # resources :cotizaciones
  get "welcome/index"

  root :to => "users#index"
  # root :to => 'panelcontrols#index'

  # devise_scope :user do
  #   get '/usuarios/sign_in', to: 'users/sessions#new', as: 'new_user_session'
  # end
  get "/compra/mis_compras/:usuario", to: "compras#mis_compras", as: "mis_compras"
  get "/cargo/excel", to: "cargos#excel", as: "cargos_excel"

  get "/rutas/ver_caminos/:id_ruta", to: "ruta#ver_caminos", as: "ruta_ver_caminos"
  get "/rutas/eliminar/:id_ruta", to: "ruta#eliminar", as: "ruta_eliminar"
  post "/rutas/guarda_camino", to: "ruta#guarda_camino", as: "ruta_guarda_camino"
  post "/rutas/crear", to: "ruta#crear", as: "ruta_crear"
  get "/rutas/muestra_funcionarios/:id_unidad", to: "ruta#muestra_funcionarios", as: "ruta_muestra_funcionario"
  get "/rutas/muestra_cargos/:id_unidad", to: "ruta#muestra_cargos", as: "ruta_muestra_cargos"
  get "/rutas/editar/:id_ruta", to: "ruta#editar", as: "ruta_editar"
  patch "/rutas/guarda_editado", to: "ruta#guarda_editado", as: "ruta_guarda_editado"

  get "/user/inicio", to: "users#inicio", as: "users_inicio"

  get "/compra/mis_tramites", to: "compras#mis_tramites", as: "compras_mis_tramites"
  get "/compra/imprime_solicitud/:id_compra", to: "compras#imprime_solicitud", as: "compras_imprime_solicitud"
  get "/compra/edita_compra/:id_compra", to: "compras#edita_compra", as: "compras_edita_compra"
  get "/compra/asignar/:id_compra", to: "compras#asignar", as: "compras_asignar"
  post "/compra/completa_solicitud", to: "compras#completa_solicitud", as: "compras_completa_solicitud"
  get "/compra/bandeja_entrada", to: "compras#bandeja_entrada", as: "compras_bandeja_entrada"
  get "/compra/carga_excepcion", to: "compras#carga_excepcion", as: "compras_carga_excepcion"
  get "/compra/ver_documento/:id_compra", to: "compras#ver_documento", as: "compras_ver_documento"
  get "/compra/ver_adjunto/:id_compra", to: "compras#ver_adjunto", as: "compras_ver_adjunto"

  get "/derivacione/ver_documento/:id_derivacion", to: "derivaciones#ver_documento", as: "derivaciones_ver_documento"
  get "/derivacione/ver_documento_rpa/:id_derivacion", to: "derivaciones#ver_documento_rpa", as: "derivaciones_ver_documento_rpa"
  post "/derivacione/guarda_derivacion", to: "derivaciones#guarda_derivacion", as: "derivaciones_guarda_derivacion"
  get "/derivacione/ver_derivaciones/:id_compra", to: "derivaciones#ver_derivaciones", as: "derivaciones_ver_derivaciones"
  get "/derivacione/ver_documento_jefe/:id_derivacion", to: "derivaciones#ver_documento_jefe", as: "derivaciones_ver_documento_jefe"
  get "/derivacione/ver_memo", to: "derivaciones#ver_memo", as: "derivaciones_ver_memo"
  post "/derivacione/genera_memo", to: "derivaciones#genera_memo", as: "derivaciones_genera_memo"
  get "/derivacione/ve_genera_memo/:id_memo", to: "derivaciones#ve_genera_memo", as: "derivaciones_ve_genera_memo"

  get "/camino/eliminar/:id_camino/:cod_ruta", to: "caminos#eliminar", as: "camino_eliminar"
  get "/camino/carga_funcionario/:proceso", to: "caminos#carga_funcionario", as: "camino_carga_funcionario"
  get "/camino/carga_funcionario_alternativo/:id_alternativo/:id_compra", to: "caminos#carga_funcionario_alternativo", as: "camino_carga_funcionario_alternativo"

  get "/documento/nuevo/:id_camino", to: "documentos#nuevo", as: "documento_nuevo"
  post "/documento/guarda_nuevo", to: "documentos#guarda_nuevo", as: "documento_guarda_nuevo"
  get "/documento/eliminar/:id_documento/:id_camino", to: "documentos#eliminar", as: "documento_eliminar"
  get "/documento/memos/:id_camino", to: "documentos#memos", as: "documento_memos"
  post "/documento/guarda_memo", to: "documentos#guarda_memo", as: "documento_gurada_memo"
  get "/documento/elimina_memo/:id_memo/:id_camino", to: "documentos#elimina_memo", as: "documento_elimina_memo"

  get "/alternativo/nuevo/:id_camino", to: "alternativos#nuevo", as: "alternativos_nuevo"
  post "/alternativo/guarda_nuevo", to: "alternativos#guarda_nuevo", as: "alternativos_guarda_nuevo"
  get "/alternativo/eliminar/:id_alternativo/:id_camino", to: "alternativos#eliminar", as: "alternativos_eliminar"
  # get "/alternativo/muestra_alternativos/:id_camino", to: "alternativos#nuevo", as: "alternativos_nuevo"

  get "/reportes/tramites", to: "reportes#tramites", as: "reporte_tramites"
  post "/reportes/por_numero", to: "reportes#por_numero", as: "reporte_por_numero"
  post "/reportes/por_usuario", to: "reportes#por_usuario", as: "reporte_por_usuario"
  post "/reportes/por_fecha", to: "reportes#por_fecha", as: "reporte_por_fecha"
  post "/reportes/por_unidad", to: "reportes#por_unidad", as: "reporte_por_unidad"

  get "/memo/imprime/:id_memo", to: "memos#imprime", as: "memo_imprime"
  # devise_for :users, path: 'auth', path_names: {  sign_out: 'logout', sign_up: 'cmon_let_me_in' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  belongs_to :unidade, optional: true
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]
  layout "template"

  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1
  # PATCH/PUT /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargos_url, notice: 'Cargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def excel
    dir = Rails.root.join("public", "excels", "unidades.xlsx")
    workbook = RubyXL::Parser.parse(dir)
    workbook.worksheets[0] # Returns first worksheet
    workbook[0]            # Returns first worksheet
    workbook["Sheet1"]     # Finds and returns worksheet titled "Sheet1"

    # importacion de cargos

    # sheet1 = workbook[0]
    # cant_filas = sheet1.sheet_data.size
    # cant_filas.times do |cont|
    #   if cont == 0
    #     puts "cabeceras"
    #   else
    #     puts "No. -- #{workbook[0][cont][0].value}"
    #     puts "Des -- #{workbook[0][cont][1].value}"
    #     mod_cargo = Cargo.new
    #     mod_cargo.descripcion = workbook[0][cont][1].value.to_s
    #     mod_cargo.save

    # fin importacion de cargos

    # importacion de unidades

    # sheet1 = workbook[0]
    # cant_filas = sheet1.sheet_data.size
    # cant_filas.times do |cont|
    #   if cont == 0
    #     puts "cabeceras"
    #   else
    #     puts "No. -- #{workbook[0][cont][0].value}"
    #     puts "Des -- #{workbook[0][cont][1].value}"
    #     mod_unidade = Unidade.new
    #     mod_unidade.descripcion = workbook[0][cont][1].value.to_s
    #     mod_unidade.save

    # fin importacion de unidades

    # importacion de personas

    sheet1 = workbook[0]
    cant_filas = sheet1.sheet_data.size
    cant_filas.times do |cont|
      if cont == 0
        puts "cabeceras"
      else
        puts "No. -- #{workbook[0][cont][0].value}"
        puts "Unidad -- #{workbook[0][cont][1].value}"
        puts "Cargo -- #{workbook[0][cont][2].value}"
        puts "Nombre -- #{workbook[0][cont][3].value}"
        mod_usuario = User.create
        unidad = Unidade.where(descripcion: workbook[0][cont][1].value)
        if unidad.present?
          mod_usuario = unidad.id
        end
        if prod
          puts "el resultado es: #{prod.nombre}"
          puts "el id es: #{prod.id}"
          p_mod = Paquete.find_by(producto_id: prod.id)
          p_mod.nombre = prod.codigo.to_s + " Caja " + workbook[0][cont][3].value.to_s + " U"
          p_mod.cantidad = workbook[0][cont][3].value
          p_mod.cantidad_real = workbook[0][cont][3].value
          p_mod.save
        end

    # fin importacion de personas

      end
    end
    # byebug
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cargo_params
      params.require(:cargo).permit(:descripcion, :nivel, :unidade_id)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_form.html.erb
<%= form_with(model: cargo, local: true) do |form| %>
  <% if cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
      <% cargo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :cargo_descripcion, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :Unidad %>
    <%= select("cargo", "unidade_id", Unidade.all.collect {|u| [ u.descripcion, u.id ] }, {include_blank: 'Seleccione Unidad'}, {class: 'form-control'}) %>
  </div>

  <div class="actions">
    <input type="submit" value="Guardar">
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Edicion de Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Mostrar', @cargo %> |
<%= link_to 'Atras', cargos_path %>

app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargos</h1>

<table class="table table-bordered" id="myTable">
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Nivel</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.descripcion %></td>
        <td>
          <% if cargo.unidade.present? %>
            <%= cargo.unidade.descripcion %>
          <% else %>
            N/T
          <% end %>
        </td>
        <td>
          <%= link_to 'Ver', cargo %>
          <%= link_to 'Editar', edit_cargo_path(cargo) %>
          <%= link_to 'Eliminar', cargo, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cargo', new_cargo_path %>

<% content_for :add_css do %>
<link href="<%= asset_path '/assets/plugins/toast-master/css/jquery.toast.css' %>" rel="stylesheet">
<link href="<%= asset_path '/assets/plugins/sweetalert/sweetalert.css' %>" rel="stylesheet" type="text/css">
<% end %>
<% content_for :add_js do %>
<script src="<%= asset_path '/assets/plugins/datatables/jquery.dataTables.min.js' %>"></script>
<script src="<%= asset_path '/js/validation.js' %>"></script>
<script src="<%= asset_path '/assets/plugins/toast-master/js/jquery.toast.js' %>"></script>
<script src="<%= asset_path '/assets/plugins/sweetalert/sweetalert.min.js' %>"></script>
<script type="text/javascript">
  var table5 = $('#myTable').DataTable({
    "oLanguage": {
      "sUrl": "https://cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
    }
  });
</script>
<% end %>

app/views/cargos/new.html.erb
<h1>New Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @cargo.descripcion %>
</p>

<p>
  <strong>Nivel:</strong>
  <%= @cargo.nivel %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>