config/routes.rb
Rails.application.routes.draw do
  resources :escogidos
  resources :memos
  resources :alternativos
  resources :docderivaciones
  resources :derivaciones
  resources :items
  resources :ruta
  resources :documentos
  resources :compras
  resources :caminos
  resources :gestiones
  resources :unidades
  resources :cargos
  # devise_for :users
  get "reportes/tramites"
  get "reportes/fechas"

  # get '/users/sign_in', to: 'users/sessions#new', as: 'new_user_session'
  # post '/users/sign_in', to: 'users/sessions#create', as: 'user_session'
  devise_for :users, path: "usuarios", controllers: {sessions: "users/sessions"}
  # devise_for :users, path: 'usuarios', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :users
  # resources :cotizaciones
  get "welcome/index"

  root :to => "users#index"
  # root :to => 'panelcontrols#index'

  # devise_scope :user do
  #   get '/usuarios/sign_in', to: 'users/sessions#new', as: 'new_user_session'
  # end
  get "/compra/mis_compras/:usuario", to: "compras#mis_compras", as: "mis_compras"
  get "/cargo/excel", to: "cargos#excel", as: "cargos_excel"

  get "/rutas/ver_caminos/:id_ruta", to: "ruta#ver_caminos", as: "ruta_ver_caminos"
  get "/rutas/eliminar/:id_ruta", to: "ruta#eliminar", as: "ruta_eliminar"
  post "/rutas/guarda_camino", to: "ruta#guarda_camino", as: "ruta_guarda_camino"
  post "/rutas/crear", to: "ruta#crear", as: "ruta_crear"
  get "/rutas/muestra_funcionarios/:id_unidad", to: "ruta#muestra_funcionarios", as: "ruta_muestra_funcionario"
  get "/rutas/muestra_cargos/:id_unidad", to: "ruta#muestra_cargos", as: "ruta_muestra_cargos"
  get "/rutas/editar/:id_ruta", to: "ruta#editar", as: "ruta_editar"
  patch "/rutas/guarda_editado", to: "ruta#guarda_editado", as: "ruta_guarda_editado"

  get "/user/inicio", to: "users#inicio", as: "users_inicio"

  get "/compra/mis_tramites", to: "compras#mis_tramites", as: "compras_mis_tramites"
  get "/compra/imprime_solicitud/:id_compra", to: "compras#imprime_solicitud", as: "compras_imprime_solicitud"
  get "/compra/edita_compra/:id_compra", to: "compras#edita_compra", as: "compras_edita_compra"
  get "/compra/asignar/:id_compra", to: "compras#asignar", as: "compras_asignar"
  post "/compra/completa_solicitud", to: "compras#completa_solicitud", as: "compras_completa_solicitud"
  get "/compra/bandeja_entrada", to: "compras#bandeja_entrada", as: "compras_bandeja_entrada"
  get "/compra/carga_excepcion", to: "compras#carga_excepcion", as: "compras_carga_excepcion"
  get "/compra/ver_documento/:id_compra", to: "compras#ver_documento", as: "compras_ver_documento"
  get "/compra/ver_adjunto/:id_compra", to: "compras#ver_adjunto", as: "compras_ver_adjunto"

  get "/derivacione/ver_documento/:id_derivacion", to: "derivaciones#ver_documento", as: "derivaciones_ver_documento"
  get "/derivacione/ver_documento_rpa/:id_derivacion", to: "derivaciones#ver_documento_rpa", as: "derivaciones_ver_documento_rpa"
  post "/derivacione/guarda_derivacion", to: "derivaciones#guarda_derivacion", as: "derivaciones_guarda_derivacion"
  get "/derivacione/ver_derivaciones/:id_compra", to: "derivaciones#ver_derivaciones", as: "derivaciones_ver_derivaciones"
  get "/derivacione/ver_documento_jefe/:id_derivacion", to: "derivaciones#ver_documento_jefe", as: "derivaciones_ver_documento_jefe"
  get "/derivacione/ver_memo", to: "derivaciones#ver_memo", as: "derivaciones_ver_memo"
  post "/derivacione/genera_memo", to: "derivaciones#genera_memo", as: "derivaciones_genera_memo"
  get "/derivacione/ve_genera_memo/:id_memo", to: "derivaciones#ve_genera_memo", as: "derivaciones_ve_genera_memo"

  get "/camino/eliminar/:id_camino/:cod_ruta", to: "caminos#eliminar", as: "camino_eliminar"
  get "/camino/carga_funcionario/:proceso", to: "caminos#carga_funcionario", as: "camino_carga_funcionario"
  get "/camino/carga_funcionario_alternativo/:id_alternativo/:id_compra", to: "caminos#carga_funcionario_alternativo", as: "camino_carga_funcionario_alternativo"

  get "/documento/nuevo/:id_camino", to: "documentos#nuevo", as: "documento_nuevo"
  post "/documento/guarda_nuevo", to: "documentos#guarda_nuevo", as: "documento_guarda_nuevo"
  get "/documento/eliminar/:id_documento/:id_camino", to: "documentos#eliminar", as: "documento_eliminar"
  get "/documento/memos/:id_camino", to: "documentos#memos", as: "documento_memos"
  post "/documento/guarda_memo", to: "documentos#guarda_memo", as: "documento_gurada_memo"
  get "/documento/elimina_memo/:id_memo/:id_camino", to: "documentos#elimina_memo", as: "documento_elimina_memo"

  get "/alternativo/nuevo/:id_camino", to: "alternativos#nuevo", as: "alternativos_nuevo"
  post "/alternativo/guarda_nuevo", to: "alternativos#guarda_nuevo", as: "alternativos_guarda_nuevo"
  get "/alternativo/eliminar/:id_alternativo/:id_camino", to: "alternativos#eliminar", as: "alternativos_eliminar"
  # get "/alternativo/muestra_alternativos/:id_camino", to: "alternativos#nuevo", as: "alternativos_nuevo"

  get "/reportes/tramites", to: "reportes#tramites", as: "reporte_tramites"
  post "/reportes/por_numero", to: "reportes#por_numero", as: "reporte_por_numero"
  post "/reportes/por_usuario", to: "reportes#por_usuario", as: "reporte_por_usuario"
  post "/reportes/por_fecha", to: "reportes#por_fecha", as: "reporte_por_fecha"
  post "/reportes/por_unidad", to: "reportes#por_unidad", as: "reporte_por_unidad"

  get "/memo/imprime/:id_memo", to: "memos#imprime", as: "memo_imprime"
  # devise_for :users, path: 'auth', path_names: {  sign_out: 'logout', sign_up: 'cmon_let_me_in' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/memo.rb
class Memo < ApplicationRecord
	belongs_to :remitente, class_name: "User", foreign_key: "remitente_id", optional: true
	has_many :escogidos
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]
  layout "template"

  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: "Memo was successfully created." }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: "Memo was successfully updated." }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url, notice: "Memo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def imprime
    # byebug
    @datos_memo = Memo.find(params[:id_memo])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_memo
    @memo = Memo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def memo_params
    params.require(:memo).permit(:docderivacione_id, :cite, :documento, :fecha)
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<%= form_with(model: memo, local: true) do |form| %>
  <% if memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :docderivacione_id %>
    <%= form.number_field :docderivacione_id, id: :memo_docderivacione_id %>
  </div>

  <div class="field">
    <%= form.label :cite %>
    <%= form.text_field :cite, id: :memo_cite %>
  </div>

  <div class="field">
    <%= form.label :documento %>
    <%= form.text_area :documento, id: :memo_documento %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha, id: :memo_fecha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/genera_memo.html.erb
<%= @datos_memo %>

app/views/memos/imprime.html.erb
<%# @datos_memo.inspect %>
<link href="<%= asset_path '/css/impresion.css' %>" rel="stylesheet" type="text/css" />

<div class="row page-titles">
  <div class="col-md-4 col-12 align-self-center">
    <h3 class="text-themecolor m-b-0 m-t-0">

    </h3>
  </div>
  <div class="col-md-4 col-12 align-self-center">

  </div>

  <div class="col-md-4  col-12 align-self-center no-imprime">

    <button class="btn pull-right btn-secondary boton-guarda-cot btn-paraimprimir" onclick="print();">
      <i class="fa fa-print"></i> IMPRIMIR
    </button>
  </div>

</div>
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="clase-impresion" style="width: 800px;">
          <table class="tabla-impresion-cabecera" border="0">
            <tr>
              <td style="width: 150px;">
                <img src="<%= asset_path '/assets/images/logo_emavias.jpg' %>" />
              </td>
              <td style="width: 600px; text-align: center;">

              </td>
            </tr>
          </table>
          <h1 style="text-align: center;">MEMORANDUM</h1>
          <br />
          <table class="tabla" border="0">
            <tr>
              <td style="width: 40%;" text-align=>
                <%= @datos_memo.fecha %>
              </td>
              <td style="width: 60%;">
                <h3>GAF - CC CITE <%= @datos_memo.cite %></h3><br />
                <table>
                  <tr>
                    <td>Para:&nbsp;&nbsp;&nbsp;</td>
                    <td>
                      <% @datos_memo.escogidos.inspect %>
                      <% @datos_memo.escogidos.each do |e| %>
                        <%= e.user.nombre %><br />
                        <b><%= e.user.cargo.descripcion %></b><br />
                      <% end %>
                    </td>
                  </tr>
                </table>
                <p>&nbsp;</p>
                <table>
                  <tr>
                    <td>De:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td>
                      <%= @datos_memo.remitente.nombre %><br />
                      <b><%= @datos_memo.remitente.cargo.descripcion %></b><br />
                    </td>
                  </tr>
                </table>

                <br /><b>Ref: Designacion de Calificacion </b>

              </td>
            </tr>
          </table>
          <hr />
          <%= @datos_memo.documento.html_safe %>
      </div>
    </div>
  </div>
</div>

app/views/memos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memos</h1>

<table>
  <thead>
    <tr>
      <th>Docderivacione</th>
      <th>Cite</th>
      <th>Documento</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.docderivacione_id %></td>
        <td><%= memo.cite %></td>
        <td><%= memo.documento %></td>
        <td><%= memo.fecha %></td>
        <td><%= link_to 'Show', memo %></td>
        <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
        <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memo', new_memo_path %>

app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Back', memos_path %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Docderivacione:</strong>
  <%= @memo.docderivacione_id %>
</p>

<p>
  <strong>Cite:</strong>
  <%= @memo.cite %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @memo.documento %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @memo.fecha %>
</p>

<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>