config/routes.rb
Rails.application.routes.draw do
  resources :escogidos
  resources :memos
  resources :alternativos
  resources :docderivaciones
  resources :derivaciones
  resources :items
  resources :ruta
  resources :documentos
  resources :compras
  resources :caminos
  resources :gestiones
  resources :unidades
  resources :cargos
  # devise_for :users
  get "reportes/tramites"
  get "reportes/fechas"

  # get '/users/sign_in', to: 'users/sessions#new', as: 'new_user_session'
  # post '/users/sign_in', to: 'users/sessions#create', as: 'user_session'
  devise_for :users, path: "usuarios", controllers: {sessions: "users/sessions"}
  # devise_for :users, path: 'usuarios', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :users
  # resources :cotizaciones
  get "welcome/index"

  root :to => "users#index"
  # root :to => 'panelcontrols#index'

  # devise_scope :user do
  #   get '/usuarios/sign_in', to: 'users/sessions#new', as: 'new_user_session'
  # end
  get "/compra/mis_compras/:usuario", to: "compras#mis_compras", as: "mis_compras"
  get "/cargo/excel", to: "cargos#excel", as: "cargos_excel"

  get "/rutas/ver_caminos/:id_ruta", to: "ruta#ver_caminos", as: "ruta_ver_caminos"
  get "/rutas/eliminar/:id_ruta", to: "ruta#eliminar", as: "ruta_eliminar"
  post "/rutas/guarda_camino", to: "ruta#guarda_camino", as: "ruta_guarda_camino"
  post "/rutas/crear", to: "ruta#crear", as: "ruta_crear"
  get "/rutas/muestra_funcionarios/:id_unidad", to: "ruta#muestra_funcionarios", as: "ruta_muestra_funcionario"
  get "/rutas/muestra_cargos/:id_unidad", to: "ruta#muestra_cargos", as: "ruta_muestra_cargos"
  get "/rutas/editar/:id_ruta", to: "ruta#editar", as: "ruta_editar"
  patch "/rutas/guarda_editado", to: "ruta#guarda_editado", as: "ruta_guarda_editado"

  get "/user/inicio", to: "users#inicio", as: "users_inicio"

  get "/compra/mis_tramites", to: "compras#mis_tramites", as: "compras_mis_tramites"
  get "/compra/imprime_solicitud/:id_compra", to: "compras#imprime_solicitud", as: "compras_imprime_solicitud"
  get "/compra/edita_compra/:id_compra", to: "compras#edita_compra", as: "compras_edita_compra"
  get "/compra/asignar/:id_compra", to: "compras#asignar", as: "compras_asignar"
  post "/compra/completa_solicitud", to: "compras#completa_solicitud", as: "compras_completa_solicitud"
  get "/compra/bandeja_entrada", to: "compras#bandeja_entrada", as: "compras_bandeja_entrada"
  get "/compra/carga_excepcion", to: "compras#carga_excepcion", as: "compras_carga_excepcion"
  get "/compra/ver_documento/:id_compra", to: "compras#ver_documento", as: "compras_ver_documento"
  get "/compra/ver_adjunto/:id_compra", to: "compras#ver_adjunto", as: "compras_ver_adjunto"

  get "/derivacione/ver_documento/:id_derivacion", to: "derivaciones#ver_documento", as: "derivaciones_ver_documento"
  get "/derivacione/ver_documento_rpa/:id_derivacion", to: "derivaciones#ver_documento_rpa", as: "derivaciones_ver_documento_rpa"
  post "/derivacione/guarda_derivacion", to: "derivaciones#guarda_derivacion", as: "derivaciones_guarda_derivacion"
  get "/derivacione/ver_derivaciones/:id_compra", to: "derivaciones#ver_derivaciones", as: "derivaciones_ver_derivaciones"
  get "/derivacione/ver_documento_jefe/:id_derivacion", to: "derivaciones#ver_documento_jefe", as: "derivaciones_ver_documento_jefe"
  get "/derivacione/ver_memo", to: "derivaciones#ver_memo", as: "derivaciones_ver_memo"
  post "/derivacione/genera_memo", to: "derivaciones#genera_memo", as: "derivaciones_genera_memo"
  get "/derivacione/ve_genera_memo/:id_memo", to: "derivaciones#ve_genera_memo", as: "derivaciones_ve_genera_memo"

  get "/camino/eliminar/:id_camino/:cod_ruta", to: "caminos#eliminar", as: "camino_eliminar"
  get "/camino/carga_funcionario/:proceso", to: "caminos#carga_funcionario", as: "camino_carga_funcionario"
  get "/camino/carga_funcionario_alternativo/:id_alternativo/:id_compra", to: "caminos#carga_funcionario_alternativo", as: "camino_carga_funcionario_alternativo"

  get "/documento/nuevo/:id_camino", to: "documentos#nuevo", as: "documento_nuevo"
  post "/documento/guarda_nuevo", to: "documentos#guarda_nuevo", as: "documento_guarda_nuevo"
  get "/documento/eliminar/:id_documento/:id_camino", to: "documentos#eliminar", as: "documento_eliminar"
  get "/documento/memos/:id_camino", to: "documentos#memos", as: "documento_memos"
  post "/documento/guarda_memo", to: "documentos#guarda_memo", as: "documento_gurada_memo"
  get "/documento/elimina_memo/:id_memo/:id_camino", to: "documentos#elimina_memo", as: "documento_elimina_memo"

  get "/alternativo/nuevo/:id_camino", to: "alternativos#nuevo", as: "alternativos_nuevo"
  post "/alternativo/guarda_nuevo", to: "alternativos#guarda_nuevo", as: "alternativos_guarda_nuevo"
  get "/alternativo/eliminar/:id_alternativo/:id_camino", to: "alternativos#eliminar", as: "alternativos_eliminar"
  # get "/alternativo/muestra_alternativos/:id_camino", to: "alternativos#nuevo", as: "alternativos_nuevo"

  get "/reportes/tramites", to: "reportes#tramites", as: "reporte_tramites"
  post "/reportes/por_numero", to: "reportes#por_numero", as: "reporte_por_numero"
  post "/reportes/por_usuario", to: "reportes#por_usuario", as: "reporte_por_usuario"
  post "/reportes/por_fecha", to: "reportes#por_fecha", as: "reporte_por_fecha"
  post "/reportes/por_unidad", to: "reportes#por_unidad", as: "reporte_por_unidad"

  get "/memo/imprime/:id_memo", to: "memos#imprime", as: "memo_imprime"
  # devise_for :users, path: 'auth', path_names: {  sign_out: 'logout', sign_up: 'cmon_let_me_in' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alternativo.rb
class Alternativo < ApplicationRecord
	belongs_to :camino, optional: true
	belongs_to :alternativo, class_name: "Ruta", foreign_key: "alternativo_id", optional: true
	belongs_to :ruta, class_name: "Ruta", foreign_key: "ruta_id", optional: true
end

app/controllers/alternativos_controller.rb
class AlternativosController < ApplicationController
  before_action :set_alternativo, only: [:show, :edit, :update, :destroy]
  layout "template"

  # GET /alternativos
  # GET /alternativos.json
  def index
    @alternativos = Alternativo.all
  end

  # GET /alternativos/1
  # GET /alternativos/1.json
  def show
  end

  # GET /alternativos/new
  def new
    @alternativo = Alternativo.new
  end

  # GET /alternativos/1/edit
  def edit
  end

  def eliminar
    Alternativo.destroy(params[:id_alternativo])
    redirect_to action: 'nuevo', id_camino: params[:id_camino] 
  end

  # POST /alternativos
  # POST /alternativos.json
  def create
    @alternativo = Alternativo.new(alternativo_params)

    respond_to do |format|
      if @alternativo.save
        format.html { redirect_to @alternativo, notice: 'Alternativo was successfully created.' }
        format.json { render :show, status: :created, location: @alternativo }
      else
        format.html { render :new }
        format.json { render json: @alternativo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alternativos/1
  # PATCH/PUT /alternativos/1.json
  def update
    respond_to do |format|
      if @alternativo.update(alternativo_params)
        format.html { redirect_to @alternativo, notice: 'Alternativo was successfully updated.' }
        format.json { render :show, status: :ok, location: @alternativo }
      else
        format.html { render :edit }
        format.json { render json: @alternativo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alternativos/1
  # DELETE /alternativos/1.json
  def destroy
    @alternativo.destroy
    respond_to do |format|
      format.html { redirect_to alternativos_url, notice: 'Alternativo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def nuevo
    @datos_camino = Camino.find(params[:id_camino])
    @listado_alternativos = Alternativo.where(camino_id: params[:id_camino])
  end

  def guarda_nuevo
    # byebug
    m_alternativo = Alternativo.new
    m_alternativo.camino_id = params[:alternativo][:camino_id]
    m_alternativo.ruta_id = params[:alternativo][:ruta_id]
    m_alternativo.alternativo_id = params[:alternativo][:alt]
    m_alternativo.save
    redirect_to action: :nuevo, id_camino: params[:alternativo][:camino_id]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alternativo
      @alternativo = Alternativo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alternativo_params
      params.require(:alternativo).permit(:ruta_id, :alternativo_id, :estado, :obs)
    end
end

app/helpers/alternativos_helper.rb
module AlternativosHelper
end

app/views/alternativos/_form.html.erb
<%= form_with(model: alternativo, local: true) do |form| %>
  <% if alternativo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alternativo.errors.count, "error") %> prohibited this alternativo from being saved:</h2>

      <ul>
      <% alternativo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ruta_id %>
    <%= form.number_field :ruta_id, id: :alternativo_ruta_id %>
  </div>

  <div class="field">
    <%= form.label :alternativo_id %>
    <%= form.number_field :alternativo_id, id: :alternativo_alternativo_id %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, id: :alternativo_estado %>
  </div>

  <div class="field">
    <%= form.label :obs %>
    <%= form.text_field :obs, id: :alternativo_obs %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alternativos/edit.html.erb
<h1>Editing Alternativo</h1>

<%= render 'form', alternativo: @alternativo %>

<%= link_to 'Show', @alternativo %> |
<%= link_to 'Back', alternativos_path %>

app/views/alternativos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alternativos</h1>

<table>
  <thead>
    <tr>
      <th>Ruta</th>
      <th>Alternativo</th>
      <th>Estado</th>
      <th>Obs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alternativos.each do |alternativo| %>
      <tr>
        <td><%= alternativo.ruta_id %></td>
        <td><%= alternativo.alternativo_id %></td>
        <td><%= alternativo.estado %></td>
        <td><%= alternativo.obs %></td>
        <td><%= link_to 'Show', alternativo %></td>
        <td><%= link_to 'Edit', edit_alternativo_path(alternativo) %></td>
        <td><%= link_to 'Destroy', alternativo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alternativo', new_alternativo_path %>

app/views/alternativos/new.html.erb
<h1>New Alternativo</h1>

<%= render 'form', alternativo: @alternativo %>

<%= link_to 'Back', alternativos_path %>

app/views/alternativos/nuevo.html.erb
<!-- <p id="notice"><%# notice %></p> -->
<% if notice.present? %>
  <div class="alert alert-success"> 
    <i class="ti-user"></i>&nbsp;&nbsp;<%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
  </div>  
<% end %>
<pre>
<% @datos_camino.inspect %>
</pre>
<div class="row page-titles">
  <div class="col-md-6 col-8 align-self-center">
    <h3 class="text-themecolor m-b-0 m-t-0">
      <span style="color: #000000;">Unidad: </span>
      <%= @datos_camino.unidade.descripcion %>
      <span style="color: #000000;">Cargo:  </span>
      <%= @datos_camino.cargo.descripcion %>
    </h3>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">

        <div class="row">
          <div class="col-md-6">

          <div class="row">
            <%= form_tag('/alternativo/guarda_nuevo') do %>
            <div class="col-md-12">
              <%= select("alternativo", "alt", Ruta.where(subruta: 1).collect {|u| [ u.nombre, u.id ] }, {include_blank: 'Seleccione Ruta'}, {class: 'form-control', required: 'required'}) %>
              <%= hidden_field_tag('alternativo[camino_id]', @datos_camino.id) %>
              <%= hidden_field_tag('alternativo[ruta_id]', @datos_camino.ruta_id) %>
              <%= submit_tag("Guardar") %>

            </div>
            
            <% end %>
          </div>
          </div>

          <div class="col-md-6">
            <% if @listado_alternativos.present? %>

            <table class="table table-bordered" id="myTable">
              <thead>
                <tr>
                  <th>Camino</th>
                  <th></th>
                </tr>
              </thead>

              <tbody>
                <%# byebug %>
                <% @listado_alternativos.each do |la| %>
                <tr>
                  <td><%= la.alternativo.nombre %></td>
                  <td>
                    <!-- <a href="<%# url_for(controller: 'documentos', action: 'nuevo', id_camino: camino.id) %>" class="btn btn-success" title="Adicionar Documentos"><i class="fa fa-files-o"></i></a>
                    <a href="<%# url_for(controller: 'alternativos', action: 'nuevo', id_ruta: camino.ruta_id) %>" class="btn btn-warning" title="Caminos Alternativos"><i class="fa fa-question-circle"></i></a> -->
                    <a href="<%= url_for(controller: 'alternativos', action: 'eliminar', id_alternativo: la.id, id_camino: la.camino_id) %>" class="btn btn-danger" title="Eliminar"><i class="fa fa-times"></i></a>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <% else %>
            No tiene unidades
            <% end %>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>


<br>
<%= link_to 'Nueva Ruta', new_rutum_path %>
<% content_for :add_css do %>
<link href="<%= asset_path '/assets/plugins/toast-master/css/jquery.toast.css' %>" rel="stylesheet">
<link href="<%= asset_path '/assets/plugins/sweetalert/sweetalert.css' %>" rel="stylesheet" type="text/css">
<% end %>
<% content_for :add_js do %>
<script src="<%= asset_path '/assets/plugins/datatables/jquery.dataTables.min.js' %>"></script>
<script src="<%= asset_path '/js/validation.js' %>"></script>
<script src="<%= asset_path '/assets/plugins/toast-master/js/jquery.toast.js' %>"></script>
<script src="<%= asset_path '/assets/plugins/sweetalert/sweetalert.min.js' %>"></script>
<script type="text/javascript">

  $( document ).ready(function() {
      // console.log( "ready!" );
      $("#camino_unidade_id").change(function(){
        //alert('Hizo cambio');
        var id_unidad = $("#camino_unidade_id").val();
        $("#carga_cargos").load( "/rutas/muestra_cargos/"+id_unidad);
      });
  });

  var table5 = $('#myTable').DataTable({
    "oLanguage": {
      "sUrl": "https://cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
    },
    aaSorting: [[2, 'asc']]
  });
</script>
<% end %>

app/views/alternativos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ruta:</strong>
  <%= @alternativo.ruta_id %>
</p>

<p>
  <strong>Alternativo:</strong>
  <%= @alternativo.alternativo_id %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @alternativo.estado %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @alternativo.obs %>
</p>

<%= link_to 'Edit', edit_alternativo_path(@alternativo) %> |
<%= link_to 'Back', alternativos_path %>